services:
  - type: web
    name: order
    env: node
    region: oregon
    plan: starter
    buildCommand: npm install
    startCommand: node server.js
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: GLIDE_API_URL
        sync: false
      - key: GLIDE_API_TOKEN
        sync: false
      - key: GLIDE_APP_ID
        sync: false
      - key: GLIDE_ORDER_LINES_TABLE_NAME
        sync: false
      - key: PORT
        value: 3000
      - key: DATABASE_URL
        fromDatabase:
          name: order-supplier-db
          property: connectionString

databases:
  - name: order-supplier-db
    region: oregon
    plan: starter 